version: 'version'

services:
  oop_db:
    image: mysql:5.7
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --init-file /docker-entrypoint-initdb.d/init.sql
    ports:
      - "3312:3306"
    environment:
      MYSQL_DATABASE: oop_db
      MYSQL_ROOT_USER: uemibk
      MYSQL_USER: uemibk
      MYSQL_ROOT_PASSWORD: Password1
      MYSQL_PASSWORD: Password1
